---
apiVersion: v1
kind: Namespace
metadata:
  name: t4
---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: t4
  labels:
    role: web-service
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: webserver
 namespace: t4
 labels:
    role: web-service
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: webserver
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 70
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: t4
  labels:
    role: web-service
spec:
  selector:
    role: web-service
  type: LoadBalancer
  ports:
  - port: 80