apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: ap-northeast-1
  version: "1.23"

vpc:
  cidr: 172.31.0.0/16

managedNodeGroups:
- name: dev-node
  amiFamily: Ubuntu2004
  instanceType: t2.micro
  desiredCapacity: 2